In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset=pd.read_csv('GroceryStoreDataSet.csv')
dataset

                MILK,BREAD,BISCUIT
0    BREAD,MILK,BISCUIT,CORNFLAKES
1              BREAD,TEA,BOURNVITA
2             JAM,MAGGI,BREAD,MILK
3                MAGGI,TEA,BISCUIT
4              BREAD,TEA,BOURNVITA
5             MAGGI,TEA,CORNFLAKES
6          MAGGI,BREAD,TEA,BISCUIT
7              JAM,MAGGI,BREAD,TEA
8                       BREAD,MILK
9   COFFEE,COCK,BISCUIT,CORNFLAKES
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11          COFFEE,SUGER,BOURNVITA
12               BREAD,COFFEE,COCK
13             BREAD,SUGER,BISCUIT
14         COFFEE,SUGER,CORNFLAKES
15           BREAD,SUGER,BOURNVITA
16              BREAD,COFFEE,SUGER
17              BREAD,COFFEE,SUGER
18      TEA,MILK,COFFEE,CORNFLAKES

In [3]:
dataset.shape

(19, 1)

In [4]:
dataset

                MILK,BREAD,BISCUIT
0    BREAD,MILK,BISCUIT,CORNFLAKES
1              BREAD,TEA,BOURNVITA
2             JAM,MAGGI,BREAD,MILK
3                MAGGI,TEA,BISCUIT
4              BREAD,TEA,BOURNVITA
5             MAGGI,TEA,CORNFLAKES
6          MAGGI,BREAD,TEA,BISCUIT
7              JAM,MAGGI,BREAD,TEA
8                       BREAD,MILK
9   COFFEE,COCK,BISCUIT,CORNFLAKES
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11          COFFEE,SUGER,BOURNVITA
12               BREAD,COFFEE,COCK
13             BREAD,SUGER,BISCUIT
14         COFFEE,SUGER,CORNFLAKES
15           BREAD,SUGER,BOURNVITA
16              BREAD,COFFEE,SUGER
17              BREAD,COFFEE,SUGER
18      TEA,MILK,COFFEE,CORNFLAKES

In [5]:
dataset.columns=['items']

In [6]:
from mlxtend.preprocessing import TransactionEncoder # OR...from mlxtend.preprocessing import OnehotTransactions
from mlxtend.frequent_patterns import apriori, association_rules

In [7]:
transactions=[]
items=dataset['items'].values
print(items)
for i in range (0,len(items)):
    transactions.append(items[i].split(","))
    
print(transactions)
encoder=TransactionEncoder()
tran=encoder.fit(transactions).transform(transactions)
print(tran)

['BREAD,MILK,BISCUIT,CORNFLAKES' 'BREAD,TEA,BOURNVITA'
 'JAM,MAGGI,BREAD,MILK' 'MAGGI,TEA,BISCUIT' 'BREAD,TEA,BOURNVITA'
 'MAGGI,TEA,CORNFLAKES' 'MAGGI,BREAD,TEA,BISCUIT' 'JAM,MAGGI,BREAD,TEA'
 'BREAD,MILK' 'COFFEE,COCK,BISCUIT,CORNFLAKES'
 'COFFEE,COCK,BISCUIT,CORNFLAKES' 'COFFEE,SUGER,BOURNVITA'
 'BREAD,COFFEE,COCK' 'BREAD,SUGER,BISCUIT' 'COFFEE,SUGER,CORNFLAKES'
 'BREAD,SUGER,BOURNVITA' 'BREAD,COFFEE,SUGER' 'BREAD,COFFEE,SUGER'
 'TEA,MILK,COFFEE,CORNFLAKES']
[['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'], ['BREAD', 'TEA', 'BOURNVITA'], ['JAM', 'MAGGI', 'BREAD', 'MILK'], ['MAGGI', 'TEA', 'BISCUIT'], ['BREAD', 'TEA', 'BOURNVITA'], ['MAGGI', 'TEA', 'CORNFLAKES'], ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'], ['JAM', 'MAGGI', 'BREAD', 'TEA'], ['BREAD', 'MILK'], ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'], ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'], ['COFFEE', 'SUGER', 'BOURNVITA'], ['BREAD', 'COFFEE', 'COCK'], ['BREAD', 'SUGER', 'BISCUIT'], ['COFFEE', 'SUGER', 'CORNFLAKES'], ['BREAD', 'SUGER', 'BOURNVITA'], ['BREAD', 'COFFEE', 'SUGER'], ['BREAD', 'COFFEE', 'SUGER'], ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]
[[ True False  True False False  True False False  True False False]
 [False  True  True False False False False False False False  True]
 [False False  True False False False  True  True  True False False]
 [ True False False False False False False  True False False  True]
 [False  True  True False False False False False False False  True]
 [False False False False False  True False  True False False  True]
 [ True False  True False False False False  True False False  True]
 [False False  True False False False  True  True False False  True]
 [False False  True False False False False False  True False False]
 [ True False False  True  True  True False False False False False]
 [ True False False  True  True  True False False False False False]
 [False  True False False  True False False False False  True False]
 [False False  True  True  True False False False False False False]
 [ True False  True False False False False False False  True False]
 [False False False False  True  True False False False  True False]
 [False  True  True False False False False False False  True False]
 [False False  True False  True False False False False  True False]
 [False False  True False  True False False False False  True False]
 [False False False False  True  True False False  True False  True]]

In [8]:
encodedData=pd.DataFrame(data = tran, columns = encoder.columns_, dtype = int)
encodedData.head(4)

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,1,0,1,0,0,1,0,0,1,0,0
1,0,1,1,0,0,0,0,0,0,0,1
2,0,0,1,0,0,0,1,1,1,0,0
3,1,0,0,0,0,0,0,1,0,0,1

In [9]:
encodedData

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,1,0,1,0,0,1,0,0,1,0,0
1,0,1,1,0,0,0,0,0,0,0,1
2,0,0,1,0,0,0,1,1,1,0,0
3,1,0,0,0,0,0,0,1,0,0,1
4,0,1,1,0,0,0,0,0,0,0,1
5,0,0,0,0,0,1,0,1,0,0,1
6,1,0,1,0,0,0,0,1,0,0,1
7,0,0,1,0,0,0,1,1,0,0,1
8,0,0,1,0,0,0,0,0,1,0,0
9,1,0,0,1,1,1,0,0,0,0,0
10,1,0,0,1,1,1,0,0,0,0,0
11,0,1,0,0,1,0,0,0,0,1,0
12,0,0,1,1,1,0,0,0,0,0,0
13,1,0,1,0,0,0,0,0,0,1,0
14,0,0,0,0,1,1,0,0,0,1,0
15,0,1,1,0,0,0,0,0,0,1,0
16,0,0,1,0,1,0,0,0,0,1,0
17,0,0,1,0,1,0,0,0,0,1,0
18,0,0,0,0,1,1,0,0,1,0,1

In [10]:
support=apriori(encodedData,min_support=0.1,use_colnames=True)
support.sort_values(by = 'support', ascending = False)

C:\Users\DELL\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                             itemsets
2   0.631579                              (BREAD)
4   0.421053                             (COFFEE)
10  0.368421                                (TEA)
0   0.315789                            (BISCUIT)
5   0.315789                         (CORNFLAKES)
9   0.315789                              (SUGER)
7   0.263158                              (MAGGI)
24  0.210526                       (SUGER, BREAD)
25  0.210526                         (TEA, BREAD)
28  0.210526                 (CORNFLAKES, COFFEE)
8   0.210526                               (MILK)
29  0.210526                      (SUGER, COFFEE)
33  0.210526                         (TEA, MAGGI)
1   0.210526                          (BOURNVITA)
20  0.157895                      (COFFEE, BREAD)
26  0.157895                       (COCK, COFFEE)
23  0.157895                        (MILK, BREAD)
22  0.157895                       (MAGGI, BREAD)
3   0.157895                               (COCK)
17  0.157895                   (BOURNVITA, BREAD)
14  0.157895                (CORNFLAKES, BISCUIT)
11  0.157895                     (BISCUIT, BREAD)
18  0.105263                   (SUGER, BOURNVITA)
42  0.105263           (CORNFLAKES, COCK, COFFEE)
41  0.105263                  (TEA, MAGGI, BREAD)
40  0.105263                  (MAGGI, JAM, BREAD)
39  0.105263               (SUGER, COFFEE, BREAD)
38  0.105263              (TEA, BOURNVITA, BREAD)
37  0.105263                (TEA, MAGGI, BISCUIT)
36  0.105263        (CORNFLAKES, BISCUIT, COFFEE)
35  0.105263          (CORNFLAKES, COCK, BISCUIT)
34  0.105263              (COCK, BISCUIT, COFFEE)
31  0.105263                    (CORNFLAKES, TEA)
32  0.105263                         (MAGGI, JAM)
19  0.105263                     (TEA, BOURNVITA)
30  0.105263                   (CORNFLAKES, MILK)
6   0.105263                                (JAM)
27  0.105263                   (CORNFLAKES, COCK)
12  0.105263                      (COCK, BISCUIT)
13  0.105263                    (BISCUIT, COFFEE)
15  0.105263                     (MAGGI, BISCUIT)
16  0.105263                       (TEA, BISCUIT)
21  0.105263                         (JAM, BREAD)
43  0.105263  (CORNFLAKES, COCK, BISCUIT, COFFEE)

In [11]:
confidence = association_rules(support, metric = 'confidence', min_threshold = 0.3)
confidence.sort_values(by = 'confidence', ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
53,"(TEA, BISCUIT)",(MAGGI),0.105263,0.263158,0.105263,1.000000,3.800000,0.077562,inf,0.823529
14,(JAM),(BREAD),0.105263,0.631579,0.105263,1.000000,1.583333,0.038781,inf,0.411765
82,"(COCK, BISCUIT, COFFEE)",(CORNFLAKES),0.105263,0.315789,0.105263,1.000000,3.166667,0.072022,inf,0.764706
36,"(COCK, BISCUIT)",(COFFEE),0.105263,0.421053,0.105263,1.000000,2.375000,0.060942,inf,0.647059
54,"(MAGGI, BISCUIT)",(TEA),0.105263,0.368421,0.105263,1.000000,2.714286,0.066482,inf,0.705882
...,...,...,...,...,...,...,...,...,...,...
40,(BISCUIT),"(COCK, COFFEE)",0.315789,0.157895,0.105263,0.333333,2.111111,0.055402,1.263158,0.769231
44,(CORNFLAKES),"(COCK, BISCUIT)",0.315789,0.105263,0.105263,0.333333,3.166667,0.072022,1.342105,1.000000
50,(CORNFLAKES),"(BISCUIT, COFFEE)",0.315789,0.105263,0.105263,0.333333,3.166667,0.072022,1.342105,1.000000
51,(BISCUIT),"(CORNFLAKES, COFFEE)",0.315789,0.210526,0.105263,0.333333,1.583333,0.038781,1.184211,0.538462
91,(BISCUIT),"(CORNFLAKES, COCK, COFFEE)",0.315789,0.105263,0.105263,0.333333,3.166667,0.072022,1.342105,1.000000